const ActionTypes = {
  // users
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',  
  LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',

  // face
  FACE_DETECT_REQUEST: 'FACE_DETECT_REQUEST',
  FACE_DETECT_SUCCESS: 'FACE_DETECT_SUCCESS',
  FACE_DETECT_FAILURE: 'FACE_DETECT_FAILURE',
}

export default ActionTypes;
